### PR TITLE
Add support to ranch_proxy_protocol in 2.2.2

### PR DESCRIPTION
**Pull request by g-andrade**

### CODE REVIEW

**Comment by lrascao** [comment]
didn't we already had proxy protocol working on cowboy?

**Comment by g-andrade** [comment]
Only on 1.0.x. This is for 2.2.x, so that we can use cowboy 2 where there's no other option.

**Comment by lrascao** [comment]
ah sou sou

**Comment by lrascao** [comment]
👍

**Comment by g-andrade** [comment]
Bump. Should I merge this?

**Pull request merged**
